import { Request, Response } from 'express';
import InspectionTopic from '../models/inspectionTopic.model';
import msg from '../constants/msg.json';

export const inspectionTopicController = {

    // Helper to generate next inspect_id (MDxxxx)
    // This is a simple implementation and might need more robust handling
    // for concurrent requests in a production environment.
    generateNextInspectId: async (): Promise<string> => {
        const lastTopic = await InspectionTopic.findOne({
            order: [['inspect_id', 'DESC']],
            attributes: ['inspect_id']
        });

        let nextNumber = 1;
        if (lastTopic && lastTopic.inspect_id) {
            const lastNum = parseInt(lastTopic.inspect_id.replace('MD', ''), 10);
            nextNumber = lastNum + 1;
        }
        return `MD${String(nextNumber).padStart(4, '0')}`;
    },

    // Create a new inspection topic
    createInspectionTopic: async (req: Request, res: Response) => {
        try {
            // Include inspectName in destructuring
            const { inspect_name, topics, method, specification } = req.body;

            // --- NEW: Check for existing inspect_name ---
            const existingInspectName = await InspectionTopic.findOne({ where: { inspect_name } });
            if (existingInspectName) {
                return res.json({
                    code: 107, // Assuming 107 is for existing ID/name
                    message: msg["107"],
                    detail: `Inspection Name '${inspect_name}' already exists`
                });
            }

            // Always generate inspectId internally
            const inspect_id = await inspectionTopicController.generateNextInspectId();

            const newTopic = await InspectionTopic.create({
                inspect_id, // Use the autogenerated inspectId
                inspect_name, // Include inspectName
                topics,
                method,
                specification,
            });

            return res.json({ code: 0, message: msg["0"], data: newTopic.get() });
        } catch (error) {
            return res.status(500).json({ code: 500, message: msg["500"], detail: `${error}` });
        }
    },

    // Get all inspection topics
    getAllInspectionTopics: async (req: Request, res: Response) => {
        try {
            const topics = await InspectionTopic.findAll({
                order: [['id', 'ASC']]
            });
            return res.json({ code: 0, message: msg["0"], data: topics });
        } catch (error) {
            return res.status(500).json({ code: 500, message: msg["500"], detail: `${error}` });
        }
    },

    // Get a single inspection topic by ID
    getInspectionTopicById: async (req: Request, res: Response) => {
        try {
            const { id } = req.params;
            const topic = await InspectionTopic.findByPk(id);

            if (!topic) {
                return res.json({ code: 101, message: msg["101"], detail: `Inspection topic with ID ${id} not found` });
            }

            return res.json({ code: 0, message: msg["0"], data: topic });
        } catch (error) {
            return res.status(500).json({ code: 500, message: msg["500"], detail: `${error}` });
        }
    },

    // Update an inspection topic
    updateInspectionTopic: async (req: Request, res: Response) => {
        try {
            const { id } = req.params;
            // Include inspect_name in destructuring
            const { inspect_name, topics, method, specification } = req.body; // Changed names

            const topic = await InspectionTopic.findByPk(id);
            if (!topic) {
                return res.json({ code: 101, message: msg["101"], detail: `Inspection topic with ID ${id} not found` });
            }


            // --- NEW: Check for existing inspect_name during update ---
            if (inspect_name && inspect_name !== topic.inspect_name) {
                const existingInspectName = await InspectionTopic.findOne({ where: { inspect_name } });
                if (existingInspectName && existingInspectName.id !== topic.id) {
                    return res.json({
                        code: 107,
                        message: msg["107"],
                        detail: `Inspection Name '${inspect_name}' already exists`
                    });
                }
            }
            // --- END NEW ---

            // Update with inspect_name
            await topic.update({ inspect_name, topics, method, specification }); // Changed names
            return res.json({ code: 0, message: msg["0"], data: topic });
        } catch (error) {
            return res.status(500).json({ code: 500, message: msg["500"], detail: `${error}` });
        }
    },

    // Delete an inspection topic
    deleteInspectionTopic: async (req: Request, res: Response) => {
        try {
            const { id } = req.params;
            const topic = await InspectionTopic.findByPk(id);

            if (!topic) {
                return res.json({ code: 101, message: msg["101"], detail: `Inspection topic with ID ${id} not found` });
            }

            await topic.destroy();
            return res.json({ code: 0, message: msg["0"] });
        } catch (error) {
            return res.status(500).json({ code: 500, message: msg["500"], detail: `${error}` });
        }
    }
};
