// import { Request, Response } from 'express';
// import OrderDetailInspectionBatch from '../models/orderDetailInspectionBatch.model';
// import OrderDetail from '../models/orderDetail.model';
// import User from '../models/user.model';
// import AuditStatus from '../models/auditStatus.model';
// import msg from '../constants/msg.json';
// import { Op } from 'sequelize'; // Import Op for Sequelize operators
// import db from '../models/db';
// import InspectionTopic from '../models/inspectionTopic.model';

// export const orderDetailInspectionBatchController = {

//     // Helper to generate next qt_code (QTymmddxxxx)
//     generateNextQtCode: async (): Promise<string> => {
//         const today = new Date();
//         const year = String(today.getFullYear()).slice(-2); // YY
//         const month = String(today.getMonth() + 1).padStart(2, '0'); // MM
//         const day = String(today.getDate()).padStart(2, '0'); // DD
//         const datePrefix = `QT${year}${month}${day}`;

//         // Find the last qt_code for today to determine the running number
//         const lastBatchToday = await OrderDetailInspectionBatch.findOne({
//             where: {
//                 qtCode: {
//                     [Op.like]: `${datePrefix}%` // Use LIKE for pattern matching
//                 },
//                 auditDate: today // Filter by today's date
//             },
//             order: [['qtCode', 'DESC']],
//             attributes: ['qtCode']
//         });

//         let nextNumber = 1;
//         if (lastBatchToday && lastBatchToday.qtCode) {
//             const lastNumStr = lastBatchToday.qtCode.slice(-4); // Get the 'xxxx' part
//             const lastNum = parseInt(lastNumStr, 10);
//             if (!isNaN(lastNum)) {
//                 nextNumber = lastNum + 1;
//             }
//         }
//         return `${datePrefix}${String(nextNumber).padStart(4, '0')}`;
//     },

//     // Create a new order detail inspection batch
//     createBatch: async (req: Request, res: Response) => {
//         try {
//             const {
//                 order_detail_id,
//                 audit_date,
//                 inspector_id,
//                 auditor_id,
//                 audit_status_id,
//                 audit_remark
//             } = req.body;
//             let { qt_code } = req.body; // Allow qt_code to be provided or autogenerated

//             // 1. Validate if OrderDetail exists
//             const orderDetail = await OrderDetail.findByPk(order_detail_id);
//             if (!orderDetail) {
//                 return res.json({
//                     code: 101,
//                     message: msg["101"],
//                     detail: `OrderDetail with ID ${order_detail_id} not found.`
//                 });
//             }

//             // 2. Validate foreign keys if provided
//             if (inspector_id) {
//                 const inspector = await User.findByPk(inspector_id);
//                 if (!inspector) return res.json({ code: 101, message: msg["101"], detail: `Inspector with ID ${inspector_id} not found.` });
//             }
//             if (auditor_id) {
//                 const auditor = await User.findByPk(auditor_id);
//                 if (!auditor) return res.json({ code: 101, message: msg["101"], detail: `Auditor with ID ${auditor_id} not found.` });
//             }
//             if (audit_status_id) {
//                 const auditStatus = await AuditStatus.findByPk(audit_status_id);
//                 if (!auditStatus) return res.json({ code: 101, message: msg["101"], detail: `Audit Status with ID ${audit_status_id} not found.` });
//             }

//             // Generate qt_code if not provided
//             if (!qt_code) {
//                 qt_code = await orderDetailInspectionBatchController.generateNextQtCode();
//             } else {
//                 // If qt_code is provided, validate its format and check for uniqueness
//                 if (!/^QT\d{10}$/.test(qt_code)) { // QTymmddxxxx (QT + 2yr + 2month + 2day + 4running)
//                     return res.json({
//                         code: 112, // Custom error code for invalid format
//                         message: msg["112"] || "Invalid QT Code format",
//                         detail: `QT Code ${qt_code} must be in QTymmddxxxx format (e.g., QT2507110001)`
//                     });
//                 }
//                 const existingBatch = await OrderDetailInspectionBatch.findOne({ where: { qtCode: qt_code } });
//                 if (existingBatch) {
//                     return res.json({
//                         code: 107, // Assuming 107 for already exists
//                         message: msg["107"],
//                         detail: `QT Code ${qt_code} already exists.`
//                     });
//                 }
//             }

//             const newBatch = await OrderDetailInspectionBatch.create({
//                 orderDetailId: order_detail_id,
//                 qtCode: qt_code,
//                 auditDate: audit_date,
//                 inspectorId: inspector_id,
//                 auditorId: auditor_id,
//                 auditStatusId: audit_status_id,
//                 auditRemark: audit_remark
//             });

//             return res.json({ code: 0, message: msg["0"], data: newBatch.get() });

//         } catch (error) {
//             return res.status(500).json({ code: 500, message: msg["500"], detail: `${error}` });
//         }
//     },

//     // Get all inspection batches, with optional filters
//     getAllBatches: async (req: Request, res: Response) => {
//         try {
//             const { orderDetailId, auditStatusId, inspectorId, auditorId, fromDate, toDate } = req.query;

//             const whereClause: any = {};
//             if (orderDetailId) whereClause.orderDetailId = orderDetailId;
//             if (auditStatusId) whereClause.auditStatusId = auditStatusId;
//             if (inspectorId) whereClause.inspectorId = inspectorId;
//             if (auditorId) whereClause.auditorId = auditorId;

//             if (fromDate || toDate) {
//                 whereClause.auditDate = {};
//                 if (fromDate) whereClause.auditDate[Op.gte] = fromDate;
//                 if (toDate) whereClause.auditDate[Op.lte] = toDate;
//             }

//             const batches = await OrderDetailInspectionBatch.findAll({
//                 where: whereClause,
//                 include: [
//                     {
//                         model: OrderDetail,
//                         as: 'orderDetail',
//                         attributes: ['id', 'order_id', 'material_id', 'amount']
//                     },
//                     {
//                         model: User,
//                         as: 'inspector',
//                         attributes: ['id', 'name', 'username']
//                     },
//                     {
//                         model: User,
//                         as: 'auditor',
//                         attributes: ['id', 'name', 'username']
//                     },
//                     {
//                         model: AuditStatus,
//                         as: 'auditStatus',
//                         attributes: ['id', 'status_code', 'status_name']
//                     },
//                     // Include inspection results if needed
//                     {
//                         model: db.OrderDetailInspectionResult, // Assuming db is accessible or imported here
//                         as: 'inspectionResults',
//                         attributes: ['id', 'inspectionTopicId', 'result'],
//                         include: [{
//                             model: InspectionTopic,
//                             as: 'inspectionTopic',
//                             attributes: ['id', 'inspect_id', 'inspect_name', 'topics']
//                         }]
//                     }
//                 ],
//                 order: [['audit_date', 'DESC'], ['qtCode', 'DESC']]
//             });
//             return res.json({ code: 0, message: msg["0"], data: batches });
//         } catch (error) {
//             return res.status(500).json({ code: 500, message: msg["500"], detail: `${error}` });
//         }
//     },

//     // Get a single inspection batch by ID
//     getBatchById: async (req: Request, res: Response) => {
//         try {
//             const { id } = req.params;

//             const batch = await OrderDetailInspectionBatch.findByPk(id, {
//                 include: [
//                     {
//                         model: OrderDetail,
//                         as: 'orderDetail',
//                         attributes: ['id', 'order_id', 'material_id', 'amount']
//                     },
//                     {
//                         model: User,
//                         as: 'inspector',
//                         attributes: ['id', 'name', 'username']
//                     },
//                     {
//                         model: User,
//                         as: 'auditor',
//                         attributes: ['id', 'name', 'username']
//                     },
//                     {
//                         model: AuditStatus,
//                         as: 'auditStatus',
//                         attributes: ['id', 'status_code', 'status_name']
//                     },
//                     {
//                         model: db.OrderDetailInspectionResult, // Assuming db is accessible or imported here
//                         as: 'inspectionResults',
//                         attributes: ['id', 'inspectionTopicId', 'result'],
//                         include: [{
//                             model: InspectionTopic,
//                             as: 'inspectionTopic',
//                             attributes: ['id', 'inspect_id', 'inspect_name', 'topics']
//                         }]
//                     }
//                 ]
//             });

//             if (!batch) {
//                 return res.json({ code: 101, message: msg["101"], detail: `Inspection Batch with ID ${id} not found.` });
//             }

//             return res.json({ code: 0, message: msg["0"], data: batch });
//         } catch (error) {
//             return res.status(500).json({ code: 500, message: msg["500"], detail: `${error}` });
//         }
//     },

//     // Update an existing inspection batch
//     updateBatch: async (req: Request, res: Response) => {
//         try {
//             const { id } = req.params;
//             const {
//                 qt_code,
//                 order_detail_id,
//                 audit_date,
//                 inspector_id,
//                 auditor_id,
//                 audit_status_id,
//                 audit_remark
//             } = req.body;

//             const batch = await OrderDetailInspectionBatch.findByPk(id);
//             if (!batch) {
//                 return res.json({ code: 101, message: msg["101"], detail: `Inspection Batch with ID ${id} not found.` });
//             }

//             // Validate foreign keys if provided and changed
//             if (order_detail_id && order_detail_id !== batch.orderDetailId) {
//                 const orderDetail = await OrderDetail.findByPk(order_detail_id);
//                 if (!orderDetail) return res.json({ code: 101, message: msg["101"], detail: `OrderDetail with ID ${order_detail_id} not found.` });
//             }
//             if (inspector_id && inspector_id !== batch.inspectorId) {
//                 const inspector = await User.findByPk(inspector_id);
//                 if (!inspector) return res.json({ code: 101, message: msg["101"], detail: `Inspector with ID ${inspector_id} not found.` });
//             }
//             if (auditor_id && auditor_id !== batch.auditorId) {
//                 const auditor = await User.findByPk(auditor_id);
//                 if (!auditor) return res.json({ code: 101, message: msg["101"], detail: `Auditor with ID ${auditor_id} not found.` });
//             }
//             if (audit_status_id && audit_status_id !== batch.auditStatusId) {
//                 const auditStatus = await AuditStatus.findByPk(audit_status_id);
//                 if (!auditStatus) return res.json({ code: 101, message: msg["101"], detail: `Audit Status with ID ${audit_status_id} not found.` });
//             }

//             // Check qt_code uniqueness if being updated
//             if (qt_code && qt_code !== batch.qtCode) {
//                 if (!/^QT\d{10}$/.test(qt_code)) {
//                     return res.json({
//                         code: 112,
//                         message: msg["112"] || "Invalid QT Code format",
//                         detail: `QT Code ${qt_code} must be in QTymmddxxxx format (e.g., QT2507110001)`
//                     });
//                 }
//                 const existingBatchWithQtCode = await OrderDetailInspectionBatch.findOne({ where: { qtCode: qt_code } });
//                 if (existingBatchWithQtCode && existingBatchWithQtCode.id !== batch.id) {
//                     return res.json({
//                         code: 107,
//                         message: msg["107"],
//                         detail: `QT Code ${qt_code} already exists.`
//                     });
//                 }
//             }

//             await batch.update({
//                 orderDetailId: order_detail_id || batch.orderDetailId,
//                 qtCode: qt_code || batch.qtCode,
//                 auditDate: audit_date || batch.auditDate,
//                 inspectorId: inspector_id || batch.inspectorId,
//                 auditorId: auditor_id || batch.auditorId,
//                 auditStatusId: audit_status_id || batch.auditStatusId,
//                 auditRemark: audit_remark !== undefined ? audit_remark : batch.auditRemark // Allow null/empty string update
//             });

//             return res.json({ code: 0, message: msg["0"], data: batch });
//         } catch (error) {
//             return res.status(500).json({ code: 500, message: msg["500"], detail: `${error}` });
//         }
//     },

//     // Delete an inspection batch
//     deleteBatch: async (req: Request, res: Response) => {
//         try {
//             const { id } = req.params;

//             const batch = await OrderDetailInspectionBatch.findByPk(id);
//             if (!batch) {
//                 return res.json({ code: 101, message: msg["101"], detail: `Inspection Batch with ID ${id} not found.` });
//             }

//             await batch.destroy();
//             return res.json({ code: 0, message: msg["0"], detail: `Inspection Batch with ID ${id} deleted successfully.` });
//         } catch (error) {
//             return res.status(500).json({ code: 500, message: msg["500"], detail: `${error}` });
//         }
//     }
// };
